language: node_js
node_js:
  - 12

cache:
  - yarn

before_install:
  - yarn install

script:
  - yarn build:ssr

after_success:
  - tar -cvf dist.tar dist/*
  - curl --ftp-create-dirs
      -u ${SFTP_USER}:${SFTP_PASSWORD}
      -T dist.tar
      ftp://frodoluo.ink/blog-dist