language: node_js
node_js:
  - 12

cache:
  - yarn

before_install:
  - yarn install

script:
  - yarn build:ssr

after_success:
  - tar -cvf dist.tar dist/*
  - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
  - curl --ftp-create-dirs
      -u ${SFTP_USER}:${SFTP_PASSWORD}
      -T dist.tar
      sftp://frodoluo.ink/var/ftp/pub/blog-dist/